version: "3.9"

services:
  amnod:
    image: armoniax/amnod:${AMNOD_IMG_VER}
    container_name: amnod-${NET}-${tag}-${id}
    working_dir: ${NODE_HOME}/amax_${NET}_${tag}
    entrypoint: ["./bin/start.sh", "$NODE_HOME/amax_${NET}_${tag}", "$PARAMs"]
    restart: always
    privileged: true
    ports: 
      - "${RPC_PORT}:8888"
      - "${P2P_PORT}:9876"
      - "${HIST_WS_PORT}:9555"
    volumes:
      - ${NODE_HOME}/amax_${NET}_${tag}_${id}/:${NODE_HOME}/amax_${NET}_${tag}/
    dns:
      - 114.114.114.114
      - 8.8.8.8
      
networks:
  default:
    name: amax
    external: true
