version: "3.9"

services:
  node:
    image: armoniax/node:${NODE_IMG_VER}
    container_name: node-${NET}-${container_id}
    working_dir: ${NODE_HOME}/amax_${NET}_${container_id}
    entrypoint: ["./bin/start.sh", "$NODE_HOME/amax_${NET}_${container_id}", ""]
    restart: always
    privileged: true
    ports: 
      - "${RPC_PORT}:8888"
      - "${P2P_PORT}:9876"
      - "${HIST_WS_PORT}:9555"
    volumes:
      - ${NODE_HOME}/amax_${NET}_${container_id}/:${NODE_HOME}/amax_${NET}_${container_id}/
    dns:
      - 114.114.114.114
      - 8.8.8.8
      
networks:
  default:
    name: flon
    external: true
