version: "3.9"

services:
  amkey:
    image: armoniax/node:${NODE_IMG_VER}
    container_name: raysvault
    working_dir: /opt/amax
    entrypoint: ["./bin/run-wallet.sh", "."]
    volumes:
      - ${host}/:/opt/amax
      - ${host}/bin/.bashrc:/root/.bashrc
    env_file:
      - .env 
    dns:
      - 114.114.114.114
      - 8.8.8.8
networks:
  default:
    name: amax
    external: true
